import "../styles/globals.css";

export const metadata = {
  title: "⏮️ Backtrack",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/fiy5ksm.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
